version: 2
jobs:
  build:
    machine: true
    working_directory: ~/dndcs-server
    steps:
      - checkout
      - run:
          name: Install Node Version Manager
          command: |
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install v10.8.0
            nvm alias default v10.8.0
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"" >> $BASH_ENV
      - run:
          name: Start Prisma server
          command: |
            npm install && npm install -g prisma
            cd prisma
            docker-compose up -d
            sleep 20
            prisma deploy --force
      - run:
          name: Run tests
          command: |
            npm run test:ci
