version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.33
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: ec2-54-246-92-116.eu-west-1.compute.amazonaws.com
            database: d8ncfd7e8c8edt
            ssl: true
            port: 5432
            user: jlugbyqedelfuj
            password: cdfcff75a30a9050d2dd84f620cb5e1ad1b01804881896714df11f0fb3b8b5de
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~